'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import React, { useState } from 'react';
import { AppstoreOutlined, MailOutlined, SettingOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { Menu } from 'antd';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import  Link  from 'next/link';

const items: MenuProps['items'] = [
  {
    label: 'Navigation One',
    key: 'mail',
    icon: <MailOutlined />,
  },
  {
    label: 'Navigation Two',
    key: 'app',
    icon: <AppstoreOutlined />,
    disabled: true,
  },
  {
    label: 'Navigation Three - Submenu',
    key: 'SubMenu',
    icon: <SettingOutlined />,
    children: [
      {
        type: 'group',
        label: 'Item 1',
        children: [
          {
            label: 'Option 1',
            key: 'setting:1',
          },
          {
            label: 'Option 2',
            key: 'setting:2',
          },
        ],
      },
      {
        type: 'group',
        label: 'Item 2',
        children: [
          {
            label: 'Option 3',
            key: 'setting:3',
          },
          {
            label: 'Option 4',
            key: 'setting:4',
          },
        ],
      },
    ],
  },
  {
    label: (
      // <a href="https://ant.design" target="_blank" rel="noopener noreferrer">
      //   Navigation Four - Link
      // </a>
      <Link href="/dashboard">
        Navigation Four - Link
      </Link>
    ),
    key: 'alipay',
  },
];

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [current, setCurrent] = useState('mail');

  const onClick: MenuProps['onClick'] = (e) => {
    console.log('click ', e);
    setCurrent(e.key);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Menu onClick={onClick} selectedKeys={[current]} mode="horizontal" items={items} />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
